# 用户评论分类

## 创建词汇表

In [22]:
#创建词汇表
import numpy as np
import pandas as pd
postingList=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],                #切分的词条
                 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
classVec = [0,1,0,1,0,1]                                                         #类别标签向量，1代表侮辱性词汇，0代表不是

## 对词条向量化

In [23]:
#词条转换为词条向量
def createVocabList(postingList):
    vocabSet= set(word for senten in postingList for word in senten) #取集合，去重复
    return list(vocabSet)


def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0] * len(vocabList)                                    #创建一个其中所含元素都为0的向量
    for word in inputSet:                                                #遍历每个词条
        if word in vocabList:                                            #如果词条存在于词汇表中，则置1
            returnVec[vocabList.index(word)] = 1
        else: print("the word: %s is not in my Vocabulary!" % word)
    return returnVec                                                    #返回文档向量
 

myVocabList = createVocabList(postingList)#词汇表，所有单词出现的集合
print('myVocabList:\n',myVocabList)
trainMat = []
for postinDoc in postingList:
    trainMat.append(setOfWords2Vec(myVocabList, postinDoc))#词条向量化
print('trainMat:\n', trainMat)

myVocabList:
 ['food', 'please', 'dalmation', 'posting', 'stupid', 'park', 'so', 'mr', 'to', 'love', 'stop', 'help', 'garbage', 'maybe', 'is', 'not', 'ate', 'quit', 'dog', 'take', 'my', 'cute', 'buying', 'flea', 'I', 'him', 'problems', 'steak', 'how', 'has', 'worthless', 'licks']
trainMat:
 [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1], [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]]


In [24]:
df=pd.DataFrame(trainMat,columns=myVocabList)
df['label']=classVec
df

food  please  dalmation  posting  stupid  park  so  mr  to  love  ...  \
0     0       1          0        0       0     0   0   0   0     0  ...   
1     0       0          0        0       1     1   0   0   1     0  ...   
2     0       0          1        0       0     0   1   0   0     1  ...   
3     0       0          0        1       1     0   0   0   0     0  ...   
4     0       0          0        0       0     0   0   1   1     0  ...   
5     1       0          0        0       1     0   0   0   0     0  ...   

   flea  I  him  problems  steak  how  has  worthless  licks  label  
0     1  0    0         1      0    0    1          0      0      0  
1     0  0    1         0      0    0    0          0      0      1  
2     0  1    1         0      0    0    0          0      0      0  
3     0  0    0         0      0    0    0          1      0      1  
4     0  0    1         0      1    1    0          0      1      0  
5     0  0    0         0      0    0    0          1      0      1  

[6 rows x 33 columns]

## 求H0和H1的先验概率

In [25]:
ph1=df['label'].sum()/len(df['label'])
ph1 #词条类别为1的概率

0.5

In [26]:
ph0=1-ph1
ph0 #词条类别为0的概率

0.5

In [27]:
df0=df[df['label']==0]#选择标签为0的所有样本
df0

food  please  dalmation  posting  stupid  park  so  mr  to  love  ...  \
0     0       1          0        0       0     0   0   0   0     0  ...   
2     0       0          1        0       0     0   1   0   0     1  ...   
4     0       0          0        0       0     0   0   1   1     0  ...   

   flea  I  him  problems  steak  how  has  worthless  licks  label  
0     1  0    0         1      0    0    1          0      0      0  
2     0  1    1         0      0    0    0          0      0      0  
4     0  0    1         0      1    1    0          0      1      0  

[3 rows x 33 columns]

In [28]:
df1=df[df['label']==1]#选择标签为1的所有样本
df1

food  please  dalmation  posting  stupid  park  so  mr  to  love  ...  \
1     0       0          0        0       1     1   0   0   1     0  ...   
3     0       0          0        1       1     0   0   0   0     0  ...   
5     1       0          0        0       1     0   0   0   0     0  ...   

   flea  I  him  problems  steak  how  has  worthless  licks  label  
1     0  0    1         0      0    0    0          0      0      1  
3     0  0    0         0      0    0    0          1      0      1  
5     0  0    0         0      0    0    0          1      0      1  

[3 rows x 33 columns]

## 求条件概率

In [29]:
p0V=np.array(df0.iloc[:,0:-1].sum(axis=0))/len(df0)# p(x|h0)
p0V

array([0.        , 0.33333333, 0.33333333, 0.        , 0.        ,
       0.        , 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.        , 0.        , 0.33333333,
       0.        , 0.33333333, 0.        , 0.33333333, 0.        ,
       1.        , 0.33333333, 0.        , 0.33333333, 0.33333333,
       0.66666667, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.        , 0.33333333])

In [30]:
p1V=np.array(df1.iloc[:,0:-1].sum(axis=0))/len(df1)# p(x|h1)
p1V

array([0.33333333, 0.        , 0.        , 0.33333333, 1.        ,
       0.33333333, 0.        , 0.        , 0.33333333, 0.        ,
       0.33333333, 0.        , 0.33333333, 0.33333333, 0.        ,
       0.33333333, 0.        , 0.33333333, 0.66666667, 0.33333333,
       0.        , 0.        , 0.33333333, 0.        , 0.        ,
       0.33333333, 0.        , 0.        , 0.        , 0.        ,
       0.66666667, 0.        ])

In [31]:
pd.DataFrame([p0V,p1V],columns=myVocabList)

food    please  dalmation   posting  stupid      park        so  \
0  0.000000  0.333333   0.333333  0.000000     0.0  0.000000  0.333333   
1  0.333333  0.000000   0.000000  0.333333     1.0  0.333333  0.000000   

         mr        to      love  ...    buying      flea         I       him  \
0  0.333333  0.333333  0.333333  ...  0.000000  0.333333  0.333333  0.666667   
1  0.000000  0.333333  0.000000  ...  0.333333  0.000000  0.000000  0.333333   

   problems     steak       how       has  worthless     licks  
0  0.333333  0.333333  0.333333  0.333333   0.000000  0.333333  
1  0.000000  0.000000  0.000000  0.000000   0.666667  0.000000  

[2 rows x 32 columns]

## 算法的改进

1.利用贝叶斯分类器对文档进行分类时，要计算多个概率的乘积以获得文档属于某个类别的概率，即计算p(w0|1)p(w1|1)p(w2|1)。如果其中有一个概率值为0，那么最后的成绩也为0。 为了降低这种影响，可以将所有词的出现数初始化为1，并将分母初始化为2。这种做法就叫做拉普拉斯平滑(Laplace Smoothing)又被称为加1平滑，是比较常用的平滑方法，它就是为了解决0概率问题  
2.下溢出问题：太多很小的数相乘，导致下溢出，结果可能变成零。 为了解决这个问题，对乘积结果取自然对数。通过求对数可以避免下溢出或者浮点数舍入导致的错误

In [32]:
#算法的改进1，分子加1，分母加2
p1V=(np.array(df1.iloc[:,0:-1].sum(axis=0))+1)/(len(df1)+2)
p0V=(np.array(df0.iloc[:,0:-1].sum(axis=0))+1)/(len(df0)+2)

In [33]:
pd.DataFrame([p0V,p1V],columns=myVocabList)

food  please  dalmation  posting  stupid  park   so   mr   to  love  ...  \
0   0.2     0.4        0.4      0.2     0.2   0.2  0.4  0.4  0.4   0.4  ...   
1   0.4     0.2        0.2      0.4     0.8   0.4  0.2  0.2  0.4   0.2  ...   

   buying  flea    I  him  problems  steak  how  has  worthless  licks  
0     0.2   0.4  0.4  0.6       0.4    0.4  0.4  0.4        0.2    0.4  
1     0.4   0.2  0.2  0.4       0.2    0.2  0.2  0.2        0.6    0.2  

[2 rows x 32 columns]

In [34]:
#算法的改进2，取log
p1V=np.log(p1V)
p0V=np.log(p0V)

In [35]:
pd.DataFrame([p0V,p1V],columns=myVocabList)

food    please  dalmation   posting    stupid      park        so  \
0 -1.609438 -0.916291  -0.916291 -1.609438 -1.609438 -1.609438 -0.916291   
1 -0.916291 -1.609438  -1.609438 -0.916291 -0.223144 -0.916291 -1.609438   

         mr        to      love  ...    buying      flea         I       him  \
0 -0.916291 -0.916291 -0.916291  ... -1.609438 -0.916291 -0.916291 -0.510826   
1 -1.609438 -0.916291 -1.609438  ... -0.916291 -1.609438 -1.609438 -0.916291   

   problems     steak       how       has  worthless     licks  
0 -0.916291 -0.916291 -0.916291 -0.916291  -1.609438 -0.916291  
1 -1.609438 -1.609438 -1.609438 -1.609438  -0.510826 -1.609438  

[2 rows x 32 columns]

## 最终测试

In [36]:
#测试1
test = ['love', 'my', 'dalmation'] 
testEntry=setOfWords2Vec(myVocabList, test)
 
p1=(p1V*testEntry).sum()+np.log(ph1)  #为1类的概率


p0=(p0V*testEntry).sum()+np.log(ph0)  #为0类的概率
if p1 > p0:
    print('侮辱类')
else:
    print('非侮辱类')

非侮辱类


In [37]:
p1V*testEntry

array([-0.        , -0.        , -1.60943791, -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -1.60943791,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -1.60943791, -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ])

In [38]:
#测试2
test = ['stupid', 'garbage']     
testEntry=setOfWords2Vec(myVocabList, test)
p1=(p1V*testEntry).sum()+np.log(ph1)
p0=(p0V*testEntry).sum()+np.log(ph0)
if p1 > p0:
    print('侮辱类')
else:
    print('非侮辱类')

侮辱类


## 最终完整代码

In [39]:
#完整代码
#训练集，标签
postingList=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],                #切分的词条
                 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
classVec = [0,1,0,1,0,1]

#向量化操作
trainMat = []
for postinDoc in postingList:
    trainMat.append(setOfWords2Vec(myVocabList, postinDoc))#词条向量化

df=pd.DataFrame(trainMat,columns=myVocabList)
df['label']=classVec

df0=df[df['label']==0]#选择标签为0的
df1=df[df['label']==1]#选择标签为0的

#算法的改进1，分子加1，分母加2
p1V=(np.array(df1.iloc[:,0:-1].sum(axis=0))+1)/(len(df1)+2)
p0V=(np.array(df0.iloc[:,0:-1].sum(axis=0))+1)/(len(df0)+2)
#算法的改进2，取log
p1V=np.log(p1V)
p0V=np.log(p0V)
                                                
#测试
test = ['love', 'my', 'dalmation'] 
testEntry=setOfWords2Vec(myVocabList, test)
p1=(p1V*testEntry).sum()+np.log(ph1)#为1类的概率
p0=(p0V*testEntry).sum()+np.log(ph0)#为0类的概率
if p1 > p0:
    print('侮辱类')
else:
    print('非侮辱类')                                              

非侮辱类


# 词向量化

## 词袋模型向量化

In [39]:
from sklearn.feature_extraction.text import CountVectorizer  
#语料，词条
corpus=["I come to  to  to China travel travel travel", 
    "This is a car to polupar in China",          
    "I love tea and to Apple ",   
    "The work is to write some papers in science"] 
vectorizer=CountVectorizer()
vectorizer.fit_transform(corpus) #稀疏矩阵形式进行存储

<4x19 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [40]:
import pandas as pd
pd.DataFrame(vectorizer.fit_transform(corpus).toarray(),columns=vectorizer.get_feature_names()) #自动去掉停用词

and  apple  car  china  come  in  is  love  papers  polupar  science  some  \
0    0      0    0      1     1   0   0     0       0        0        0     0   
1    0      0    1      1     0   1   1     0       0        1        0     0   
2    1      1    0      0     0   0   0     1       0        0        0     0   
3    0      0    0      0     0   1   1     0       1        0        1     1   

   tea  the  this  to  travel  work  write  
0    0    0     0   3       3     0      0  
1    0    0     1   1       0     0      0  
2    1    0     0   1       0     0      0  
3    0    1     0   1       0     1      1

## TF-IDF模型

In [43]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
corpus=["I come to  to  to China travel travel travel", 
    "This is a car to polupar in China",          
    "I love tea and to Apple ",   
    "The work is to write some papers in science"] 
tfidf = TfidfVectorizer()
re = tfidf.fit_transform(corpus)
re

<4x19 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [66]:
#TF-IDF模型
import pandas as pd
pd.DataFrame(re.toarray(),columns=tfidf.get_feature_names())

and     apple       car     china     come        in        is  \
0  0.000000  0.000000  0.000000  0.218059  0.27658  0.000000  0.000000   
1  0.000000  0.000000  0.441206  0.347852  0.00000  0.347852  0.347852   
2  0.483803  0.483803  0.000000  0.000000  0.00000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.00000  0.287590  0.287590   

       love    papers   polupar   science      some       tea       the  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.441206  0.000000  0.000000  0.000000  0.000000   
2  0.483803  0.000000  0.000000  0.000000  0.000000  0.483803  0.000000   
3  0.000000  0.364772  0.000000  0.364772  0.364772  0.000000  0.364772   

       this        to    travel      work     write  
0  0.000000  0.432993  0.829741  0.000000  0.000000  
1  0.441206  0.230239  0.000000  0.000000  0.000000  
2  0.000000  0.252468  0.000000  0.000000  0.000000  
3  0.000000  0.190353  0.000000  0.364772  0.364772

## 中文处理

In [42]:
import jieba  #结巴
jieba.lcut('结婚的和尚未结婚的') #分词

['结婚', '的', '和', '尚未', '结婚', '的']

In [43]:
' '.join(jieba.lcut('结婚的和尚未结婚的'))

'结婚 的 和 尚未 结婚 的'

In [44]:
import jieba  #结巴
corpus=["我喜欢去中国旅游", 
    "这个车在中国很流行",          
    "我喜欢茶叶和苹果",   
    "这个工作是写一些科技文献"] 
newcorpus=[' '.join(jieba.lcut(sen)) for sen in corpus]
newcorpus

['我 喜欢 去 中国 旅游', '这个 车 在 中国 很 流行', '我 喜欢 茶叶 和 苹果', '这个 工作 是 写 一些 科技 文献']

In [45]:
vectorizer=CountVectorizer()
pd.DataFrame(vectorizer.fit_transform(newcorpus).toarray(),columns=vectorizer.get_feature_names())

一些  中国  喜欢  工作  文献  旅游  流行  科技  苹果  茶叶  这个
0   0   1   1   0   0   1   0   0   0   0   0
1   0   1   0   0   0   0   1   0   0   0   1
2   0   0   1   0   0   0   0   0   1   1   0
3   1   0   0   1   1   0   0   1   0   0   1

# sklearn中的贝叶斯

## 多项式模型

In [48]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
seed=10
X = np.random.randint(5, size=(10, 10))
y = np.array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4])
clf = MultinomialNB()
clf.fit(X, y)
print(clf.predict([[1,1,1,1,1,1,1,1,1,1]]))

[3]


In [47]:
X

array([[2, 2, 4, 3, 4, 1, 4, 4, 1, 0],
       [3, 0, 1, 2, 1, 4, 3, 3, 1, 3],
       [4, 0, 4, 4, 2, 1, 4, 2, 3, 2],
       [3, 1, 3, 4, 4, 0, 1, 0, 3, 0],
       [4, 0, 0, 3, 3, 0, 4, 0, 3, 4],
       [0, 4, 2, 3, 2, 0, 4, 2, 4, 4],
       [0, 2, 0, 1, 3, 2, 4, 1, 4, 4],
       [0, 1, 0, 3, 4, 2, 2, 0, 3, 1],
       [1, 4, 4, 0, 4, 3, 0, 3, 2, 1],
       [1, 2, 1, 3, 1, 2, 0, 2, 4, 4]])

In [49]:
clf.predict_proba([[1,1,1,1,1,1,1,1,1,1]])

array([[0.26182584, 0.06671389, 0.37091454, 0.16064312, 0.09667629,
        0.04322631]])

## 伯努利模型

In [50]:
from sklearn.naive_bayes import BernoulliNB
import numpy as np
X = np.random.randint(2, size=(6, 10))
Y = np.array([1, 2, 3, 4, 4, 5])

clf = BernoulliNB()
clf.fit(X, Y)
print(clf.predict(X[2:3]))

[3]


In [51]:
X

array([[0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 1, 1]])

## 高斯模型，鸢尾花分类

In [52]:
# 导入算法包以及数据集
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.naive_bayes import GaussianNB

In [55]:
# 载入数据
iris = datasets.load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target,random_state=10) 

In [56]:
mul_nb = GaussianNB()
mul_nb.fit(x_train,y_train)#训练，拟合

GaussianNB(priors=None, var_smoothing=1e-09)

In [57]:
mul_nb.predict(x_test)#预测

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2])

In [58]:
mul_nb.score(x_test,y_test)#模型得分，准确率

1.0

In [59]:
print(confusion_matrix(y_test,mul_nb.predict(x_test)))#混淆矩阵

[[11  0  0]
 [ 0 15  0]
 [ 0  0 12]]


In [60]:
print(classification_report(y_test,mul_nb.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



# 英文新闻分类，20newsgroups
20 newsgroups数据集18000篇新闻文章，一共涉及到20种话题，所以称作20 newsgroups text dataset，分为两部分：训练集和测试集，通常用来做文本分类.

fetch_20newsgroups的参数设置：
fetch_20newsgroups(data_home=None, # 文件下载的路径
                   subset='train', # 加载那一部分数据集 train/test
                   categories=None, # 选取哪一类数据集[类别列表]，默认20类
                   shuffle=True,  # 将数据集随机排序
                   random_state=42, # 随机数生成器
                   remove=(), # ('headers','footers','quotes') 去除部分文本
                   download_if_missing=True # 如果没有下载过，重新下载
                   )

## 读取数据

In [62]:
import os
os.chdir(r'D:\CDA\File')
from sklearn.datasets import fetch_20newsgroups  #20newsbydate.tar.gz
news = fetch_20newsgroups(data_home=r'D:\CDA\File',subset='all' )

In [64]:
len(news.data) #总的文本数目

18846

In [66]:
news.data[0]#第一篇文章内容

"From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>\nSubject: Pens fans reactions\nOrganization: Post Office, Carnegie Mellon, Pittsburgh, PA\nLines: 12\nNNTP-Posting-Host: po4.andrew.cmu.edu\n\n\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n"

In [67]:
news.target #类别编号

array([10,  3, 17, ...,  3,  1,  7])

In [68]:
news.target.shape#总数,label数量

(18846,)

In [69]:
news.target_names#新闻的类别

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

## 特征提取

In [70]:
#将文本转为TF-IDF向量
from sklearn.feature_extraction.text import TfidfVectorizer
# 提取tfidf特征
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(news.data)
vectors

<18846x173762 sparse matrix of type '<class 'numpy.float64'>'
	with 2952534 stored elements in Compressed Sparse Row format>

In [71]:
vectors[0,:]#稀疏矩阵

<1x173762 sparse matrix of type '<class 'numpy.float64'>'
	with 110 stored elements in Compressed Sparse Row format>

## 训练集和测试集分别处理

In [72]:
news_train = fetch_20newsgroups(data_home=r'D:\CDA\File',subset='train' ) #训练集
news_test = fetch_20newsgroups(data_home=r'D:\CDA\File',subset='test' )   #测试集

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectors_train = vectorizer.fit_transform(news_train.data)   #训练集特征提取
vectors_train

<11314x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [78]:
vectors_test = vectorizer.transform(news_test.data)         #测试集特征提取
vectors_test

<7532x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 1107956 stored elements in Compressed Sparse Row format>

In [86]:
#简单的测试模型
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB
nb = MultinomialNB()
nb.fit(vectors_train, news_train.target)
nb.score(vectors_test, news_test.target)

0.7738980350504514

## 优化参数，网格搜索优化参数

In [79]:
from sklearn.model_selection import GridSearchCV
nb = MultinomialNB()
params={'alpha':np.linspace(0,0.5,50)}
grid_search=GridSearchCV(nb,param_grid=params,cv=5,verbose=2,n_jobs=-1)
grid_search.fit(vectors_train, news_train.target)
grid_search.best_params_

Fitting 5 folds for each of 50 candidates, totalling 250 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    5.5s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 250 out of 250 | elapsed:   20.2s finished


{'alpha': 0.01020408163265306}

In [80]:
grid_search.score(vectors_test, news_test.target)

0.8352363250132767

## 增加停用词

In [86]:
#添加停用词
def get_stop_words():
    result = set()
    for line in open(r'D:\CDA\File\stopwords_en.txt','r').readlines():
        result.add(line.strip())
    return result
# 加载停用词
stop_words = get_stop_words()
stop_words

{'a',
 'about',
 'after',
 'again',
 'against',
 'all',
 'almost',
 'along',
 'also',
 'although',
 'always',
 'among',
 'an',
 'and',
 'another',
 'any',
 'are',
 'area',
 'around',
 'as',
 'asked',
 'at',
 'away',
 'back',
 'be',
 'because',
 'become',
 'been',
 'before',
 'began',
 'being',
 'best',
 'better',
 'between',
 'big',
 'both',
 'business',
 'but',
 'by',
 'camQ',
 'can',
 'case',
 'certain',
 'come',
 'could',
 'day',
 'did',
 'different',
 'do',
 'does',
 'done',
 'door',
 'down',
 'during',
 'each',
 'early',
 'end',
 'enough',
 'even',
 'ever',
 'every',
 'eyes',
 'face',
 'fact',
 'family',
 'far',
 'felt',
 'few',
 'find',
 'first',
 'for',
 'four',
 'from',
 'general',
 'get',
 'give',
 'given',
 'go',
 'god',
 'going',
 'good',
 'got',
 'great',
 'group',
 'had',
 'hand',
 'has',
 'have',
 'he',
 'head',
 'help',
 'her',
 'here',
 'high',
 'him',
 'himself',
 'his',
 'home',
 'house',
 'how',
 'however',
 'i',
 'if',
 'important',
 'in',
 'interest',
 'into',
 'is

In [82]:
vectorizer = TfidfVectorizer(stop_words=stop_words)
vectors_train = vectorizer.fit_transform(news_train.data)
vectors_train

D:\conda\lib\site-packages\sklearn\feature_extraction\text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['camq', 're'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


<11314x129834 sparse matrix of type '<class 'numpy.float64'>'
	with 1248887 stored elements in Compressed Sparse Row format>

In [83]:
vectors_test = vectorizer.transform(news_test.data)         #测试集特征提取

In [84]:
from sklearn.model_selection import GridSearchCV
nb = MultinomialNB()
params={'alpha':np.linspace(0,0.5,50)}
grid_search=GridSearchCV(nb,param_grid=params,cv=5,verbose=2,n_jobs=-1)
grid_search.fit(vectors_train, news_train.target)
grid_search.best_params_

Fitting 5 folds for each of 50 candidates, totalling 250 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    5.3s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   12.3s
[Parallel(n_jobs=-1)]: Done 250 out of 250 | elapsed:   18.3s finished


{'alpha': 0.030612244897959183}

In [85]:
grid_search.score(vectors_test, news_test.target)

0.8372278279341476

# 中文分类

In [ ]:
中文处理流程：
1、分词，转换为用空格分开的字符串列表
2、加载停用词
3、向量化
4、建模
5、调参
6、测试